#ifndef _NanoGL_CONFIG_H
#define _NanoGL_CONFIG_H

#define UNOFFICIAL_HACK_ENABLE_NEAREST_RESIZE 1
#define UNOFFICIAL_HACK_ENABLE_TRANSFORM_WORLD 1
#define UNOFFICIAL_HACK_FILL_COLOR_AFFECTS_THE_IMAGE_PATTERN 1

#endif

