CC=gcc
CP=cp
ICONV=iconv
MKDIR=mkdir
SRCS=$(wildcard ../Example/*.c)
TARGET=$(subst ../Example,./Example,$(SRCS:%.c=%.exe))
CFLAGS= -std=c99 -I../src
LDFLAGS=-L../lib -lnanogl -lglfw3 -lmad -lglew -framework OpenGL -framework Foundation -framework IOKit -framework CoreVideo -framework CoreAudio -framework Cocoa -framework AudioUnit -framework AudioToolBox -framework OpenAL -framework AppKit

all: ./Example $(TARGET)

./Example:
	if [ ! -d ./Example ] ; then $(MKDIR) ./Example ; fi &&\
	if [ ! -d ./Example/Sound ] ; then $(CP) -rf ../Example/Sound ./Example; fi &&\
	if [ ! -d ./Example/Image ] ; then $(CP) -rf ../Example/Image ./Example ; fi &&\
	if [ ! -d ./Example/Font ] ; then $(CP) -rf ../Example/Font ./Example ; fi

./Example/%.c: ../Example/%.c
	$(ICONV) -f sjis -t utf8 $^ > $@

./Example/%.exe: ./Example/%.c
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

clean:
	rm $(TARGET)

